# Generated by Django 5.0.2 on 2024-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='nombreLibro',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
